[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "contracts/=src/contracts/",
    "script/=script/",
    "src/=src/",
    "foundry-devops/=lib/foundry-devops/",
    "forge-std/=lib/forge-std/src/"
]
ffi = true #enables foundry to tun commands
[rpc_endpoints]
linea-sepolia = "https://linea-sepolia.infura.io/v3/${INFURA_API_KEY}"
[etherscan]
linea-testnet = { key = "${LINEASCAN_API_KEY}", url = "https://api-sepolia.lineascan.build/api" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
